success: "&aПроверка успешно пройдена!"
hours: 72
message: "Пожалуйста перейдите по ссылке решите рекапчу с устройства на котором вы играете: {url}"
site: "https://109.172.91.185:7777/v2652166.hosted-by-vdsina.ru"
key: ""
titleOn: true
title: "Проверка"
subTittle: "Перейдите по ссылке в чате и пройдите рекапчу, ПКМ по ссылке."
titleNo: "Проверка"
subTittleNo: "Проверка пройдена, поздравляем!"
serverCommands: []
playerCommands: []